# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [28]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

In [12]:
#installing dependencies if needed

#!conda install gmaps -c conda-forge

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [24]:
#!jupyter nbextension enable --py gmaps

Enabling notebook extension jupyter-gmaps/extension...
      - Validating: ok

In [61]:
# Load the csv exported in Part I to a DataFrame

weather_csv_file = "../WeatherPy/output_data/cityweatherdata.csv"

weatherdf = pd.read_csv(weather_csv_file)

weatherdf.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Wind deg,Sunrise,Sunset,Visibility,Temp
0,provideniya,64.3833,-173.3000,-13.23,83.0,99.0,7.67,RU,1.612035e+09,58.0,1.612124e+09,1.612149e+09,10000.0,-13.23
1,inirida,3.8653,-67.9239,93.69,42.0,100.0,2.80,CO,1.612035e+09,24.0,1.612004e+09,1.612047e+09,10000.0,93.69
2,gannan,47.9147,123.5031,-12.14,89.0,100.0,3.40,CN,1.612035e+09,131.0,1.612049e+09,1.612083e+09,10000.0,-12.14
3,yulara,-25.2406,130.9889,84.20,37.0,40.0,12.66,AU,1.612035e+09,100.0,1.612040e+09,1.612088e+09,10000.0,84.20
4,puerto ayora,-0.7393,-90.3518,86.00,66.0,0.0,16.11,EC,1.612035e+09,130.0,1.612009e+09,1.612052e+09,10000.0,83.52

In [62]:
weatherdf.count()

City          559
Lat           559
Lng           559
Max Temp      559
Humidity      559
Cloudiness    559
Wind Speed    559
Country       556
Date          559
Wind deg      559
Sunrise       559
Sunset        559
Visibility    559
Temp          559
dtype: int64

In [63]:
#drop NaN values

weatherdf1 = weatherdf.dropna()
weatherdf1.count()

City          556
Lat           556
Lng           556
Max Temp      556
Humidity      556
Cloudiness    556
Wind Speed    556
Country       556
Date          556
Wind deg      556
Sunrise       556
Sunset        556
Visibility    556
Temp          556
dtype: int64

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [64]:
# Configure gmaps with API key.
gmaps.configure(api_key=g_key)

In [65]:
locations
weatherdf1.columns
humidity

0      83.0
1      42.0
2      89.0
3      37.0
4      66.0
       ...
554    94.0
555    81.0
556    63.0
557    96.0
558    92.0
Name: Humidity, Length: 556, dtype: float64

In [66]:

# Convert Humidity to float and store
humidity = weatherdf1["Humidity"].astype(float)

# Store 'Latitude' and 'Longitude' into  locations. 
locations = weatherdf1[["Lat", "Lng"]].astype(float)

# Create a humidity Heatmap layer
# Plot Heatmap
fig = gmaps.figure(center = [0,0] ,zoom_level = 2)
# Create and add heat layer 
heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                               dissipating=False, max_intensity=100,
                               point_radius = 3)
fig.add_layer(heat_layer)
#Display figure
fig
# see humidity map in the Output Data folder for image

Figure(layout=FigureLayout(height='420px'))

In [21]:
locations

         Lat       Lng
0    64.3833 -173.3000
1     3.8653  -67.9239
2    47.9147  123.5031
3   -25.2406  130.9889
4    -0.7393  -90.3518
..       ...       ...
554  37.2398  -96.9956
555  44.8333    0.5000
556  31.4165   31.8133
557  -3.6000   26.6667
558  -6.4167   20.8000

[556 rows x 2 columns]

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [67]:
# Narrow down the DataFrame to find your ideal weather condition.
vacayweatherdf = weatherdf1

# Drop any rows that don't contain all three conditions. Want to be sure the weather is ideal.

# A max temperature lower than 85 degrees but higher than 69.
vacayweatherdf = vacayweatherdf.loc[(vacayweatherdf["Max Temp"] < 85) & (vacayweatherdf["Max Temp"] > 69)]

# Wind speed less than 10 mph.
vacayweatherdf = vacayweatherdf.loc[vacayweatherdf["Wind Speed"] < 9.69]

# Zero cloudiness.
vacayweatherdf = vacayweatherdf.loc[vacayweatherdf["Cloudiness"] == 0]

# Drop any rows with null values
vacayweatherdf = vacayweatherdf.dropna()

vacayweatherdf

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Wind deg,Sunrise,Sunset,Visibility,Temp
5,pisco,-13.7000,-76.2167,79.00,65.0,0.0,6.91,PE,1.612035e+09,270.0,1.612004e+09,1.612050e+09,10000.0,77.83
21,saint-philippe,-21.3585,55.7679,78.80,65.0,0.0,4.61,RE,1.612035e+09,80.0,1.611972e+09,1.612019e+09,10000.0,73.83
113,tchaourou,8.8865,2.5975,81.88,16.0,0.0,4.27,BJ,1.612035e+09,18.0,1.611987e+09,1.612029e+09,10000.0,81.88
174,dapaong,10.8639,0.2050,81.70,15.0,0.0,6.67,TG,1.612035e+09,8.0,1.611988e+09,1.612030e+09,10000.0,81.70
259,sindou,10.6667,-5.1667,80.22,15.0,0.0,4.81,BF,1.612035e+09,22.0,1.611989e+09,1.612031e+09,10000.0,80.22
279,kidal,18.4411,1.4078,69.57,20.0,0.0,8.93,ML,1.612035e+09,88.0,1.611988e+09,1.612029e+09,10000.0,69.57
287,caravelas,-17.7125,-39.2481,81.12,68.0,0.0,8.70,BR,1.612035e+09,78.0,1.611995e+09,1.612041e+09,10000.0,81.12
302,boromo,11.7500,-2.9333,82.72,14.0,0.0,6.96,BF,1.612035e+09,19.0,1.611989e+09,1.612030e+09,10000.0,82.72
324,kulhudhuffushi,6.6221,73.0700,81.73,68.0,0.0,7.49,MV,1.612035e+09,47.0,1.612056e+09,1.612099e+09,10000.0,81.73
349,cap malheureux,-19.9842,57.6142,79.00,85.0,0.0,5.01,MU,1.612035e+09,117.0,1.611972e+09,1.612018e+09,10000.0,79.00
398,grand gaube,-20.0064,57.6608,79.00,85.0,0.0,5.01,MU,1.612035e+09,117.0,1.611972e+09,1.612018e+09,10000.0,79.00
420,wukari,7.8500,9.7833,81.00,16.0,0.0,2.66,NG,1.612035e+09,347.0,1.611985e+09,1.612028e+09,10000.0,81.00
444,najran,17.4924,44.1277,69.80,24.0,0.0,4.61,SA,1.612035e+09,40.0,1.611978e+09,1.612019e+09,10000.0,69.80
473,berbera,10.4396,45.0143,74.48,75.0,0.0,7.02,SO,1.612035e+09,50.0,1.611977e+09,1.612019e+09,10000.0,74.48
474,salalah,17.0151,54.0924,71.60,56.0,0.0,5.75,OM,1.612035e+09,360.0,1.611975e+09,1.612016e+09,10000.0,71.60
480,saint-pierre,-21.3393,55.4781,78.80,65.0,0.0,4.61,RE,1.612035e+09,80.0,1.611972e+09,1.612019e+09,10000.0,74.71
500,saint-joseph,-21.3667,55.6167,78.80,65.0,0.0,4.61,RE,1.612035e+09,80.0,1.611972e+09,1.612019e+09,10000.0,73.94
512,upington,-28.4478,21.2561,80.60,18.0,0.0,5.75,ZA,1.612035e+09,200.0,1.611979e+09,1.612028e+09,10000.0,80.60
527,providencia,28.7167,-111.5833,69.01,48.0,0.0,5.99,MX,1.612035e+09,270.0,1.612016e+09,1.612055e+09,10000.0,68.22

In [69]:
vacayweatherdf.count()

City          19
Lat           19
Lng           19
Max Temp      19
Humidity      19
Cloudiness    19
Wind Speed    19
Country       19
Date          19
Wind deg      19
Sunrise       19
Sunset        19
Visibility    19
Temp          19
dtype: int64

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [71]:
hotel_df = vacayweatherdf

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    print(f"Retrieving Results for Index {index}: {row['City']}.")
    response = requests.get(base_url, params=params).json()
    # print(json.dumps(response, indent=4, sort_keys=True))
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        hotel_df.loc[index, 'Hotel Address'] = results[0]['vicinity']
        
    except (KeyError, IndexError):
        print("Missing field/result..... skipping.")
        
    print("-"*69)

Retrieving Results for Index 5: pisco.
Closest hotel is Hotel San Isidro Oficial.
---------------------------------------------------------------------
Retrieving Results for Index 21: saint-philippe.
Closest hotel is Chambres d'hôte "La Trinité".
---------------------------------------------------------------------
Retrieving Results for Index 113: tchaourou.
Closest hotel is SAFIR HOTEL.
---------------------------------------------------------------------
Retrieving Results for Index 174: dapaong.
Closest hotel is Hotel Caroli.
---------------------------------------------------------------------
Retrieving Results for Index 259: sindou.
Closest hotel is LERABA HOTEL.
---------------------------------------------------------------------
Retrieving Results for Index 279: kidal.
Missing field/result..... skipping.
---------------------------------------------------------------------
Retrieving Results for Index 287: caravelas.
Closest hotel is Pousada dos Navegantes.
---------------------------------------------------------------------
Retrieving Results for Index 302: boromo.
Closest hotel is Sama Camp.
---------------------------------------------------------------------
Retrieving Results for Index 324: kulhudhuffushi.
Closest hotel is Haajy Guest House 1.
---------------------------------------------------------------------
Retrieving Results for Index 349: cap malheureux.
Closest hotel is Pereybere Hotel & Spa.
---------------------------------------------------------------------
Retrieving Results for Index 398: grand gaube.
Closest hotel is Veranda Paul et Virginie Hotel & Spa.
---------------------------------------------------------------------
Retrieving Results for Index 420: wukari.
Closest hotel is Elimtop.
---------------------------------------------------------------------
Retrieving Results for Index 444: najran.
Closest hotel is محمد هادي ال فطيح.
---------------------------------------------------------------------
Retrieving Results for Index 473: berbera.
Closest hotel is IBCO REAL ESTATE PROPERTY.
---------------------------------------------------------------------
Retrieving Results for Index 474: salalah.
Closest hotel is HAMDAN PLAZA HOTEL SALALAH.
---------------------------------------------------------------------
Retrieving Results for Index 480: saint-pierre.
Closest hotel is Lindsey Hôtel.
---------------------------------------------------------------------
Retrieving Results for Index 500: saint-joseph.
Closest hotel is "Plantation Bed and Breakfast.
---------------------------------------------------------------------
Retrieving Results for Index 512: upington.
Closest hotel is River Place Manor.
---------------------------------------------------------------------
Retrieving Results for Index 527: providencia.
Missing field/result..... skipping.
---------------------------------------------------------------------

In [72]:
hotel_df.count()

City             19
Lat              19
Lng              19
Max Temp         19
Humidity         19
Cloudiness       19
Wind Speed       19
Country          19
Date             19
Wind deg         19
Sunrise          19
Sunset           19
Visibility       19
Temp             19
Hotel Name       17
Hotel Address    17
dtype: int64

In [73]:
hoteldf1 = hotel_df

In [74]:
hotel_df = hotel_df.dropna()
hotel_df.count()

City             17
Lat              17
Lng              17
Max Temp         17
Humidity         17
Cloudiness       17
Wind Speed       17
Country          17
Date             17
Wind deg         17
Sunrise          17
Sunset           17
Visibility       17
Temp             17
Hotel Name       17
Hotel Address    17
dtype: int64

In [75]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [76]:
locations.head()

         Lat      Lng
5   -13.7000 -76.2167
21  -21.3585  55.7679
113   8.8865   2.5975
174  10.8639   0.2050
259  10.6667  -5.1667

In [77]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)

# Add the layer to the map
fig.add_layer(markers)

# Display Map
fig
#image saved in the output folder as Hotel Map.

Figure(layout=FigureLayout(height='420px'))